ci(release): try stripping `riscv` more

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -19,15 +19,15 @@ jobs:
         include:
           - { target: x86_64-unknown-linux-gnu, runs-on: ubuntu-22.04 }
           - { target: aarch64-unknown-linux-gnu, runs-on: ubuntu-22.04-arm }
-          - { target: riscv64gc-unknown-linux-gnu, runs-on: ubuntu-22.04-arm, build: zigbuild }
+          - { target: riscv64gc-unknown-linux-gnu, runs-on: ubuntu-22.04-arm, build: zigbuild, deps: binutils-riscv64-linux-gnu }
 
           - { target: x86_64-unknown-linux-musl, runs-on: ubuntu-22.04, build: zigbuild, args: --features=mimalloc }
           - { target: aarch64-unknown-linux-musl, runs-on: ubuntu-22.04-arm, build: zigbuild, args: --features=mimalloc }
-          - { target: riscv64gc-unknown-linux-musl, runs-on: ubuntu-22.04-arm, build: zigbuild, args: --features=mimalloc }
+          - { target: riscv64gc-unknown-linux-musl, runs-on: ubuntu-22.04-arm, build: zigbuild, args: --features=mimalloc, deps: binutils-riscv64-linux-gnu }
  
     steps:
     - name: Install dependencies
-      run: sudo apt-get update && sudo apt-get install -y clang
+      run: sudo apt-get update && sudo apt-get install -y clang ${{ matrix.deps }}
 
     - name: Checkout code
       uses: actions/checkout@v4
@@ -66,7 +66,7 @@ jobs:
         cp "target/${{ matrix.target }}/dist/wild" "$n"
         cp README.md LICENSE* CHANGELOG.md "$n"
         strings "$n/wild" | grep "Linker: Wild"
-        strip "$n/wild"
+        strip "$n/wild" || riscv64-linux-gnu-strip "$n/wild" || echo "::warning::couldn't strip binary"
         tar zcf $n.tar.gz $n
 
     - name: Release
